package com.lhfeiyu.po;

import java.util.Date;

public class PhrBasicInfo {
	
	
	private Boolean mine;
	
	
    public Boolean getMine() {
		return mine;
	}

	public void setMine(Boolean mine) {
		this.mine = mine;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.id
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.name
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.user_no
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.sex
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.birthday
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.id_card_no
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String idCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.work_unit
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String workUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.tel
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.linkman
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.linkman_tel
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String linkmanTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.resident_type
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String residentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.nation
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.nation_name
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String nationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.blood_type
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String bloodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.rh_type
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String rhType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.degree
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.profession
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String profession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.marital_status
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String maritalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.pay_type
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.pay_type_other
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String payTypeOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.ywgms
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String ywgms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.ywgms_name
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String ywgmsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.bls
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String bls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.jws_disease_des
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String jwsDiseaseDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.jws_operation_des
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String jwsOperationDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.jws_trauma_des
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String jwsTraumaDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.jws_transfusion_des
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String jwsTransfusionDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.jzs_fq
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String jzsFq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.jzs_mq
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String jzsMq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.jzs_xdjm
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String jzsXdjm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.jzs_zn
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String jzsZn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.ycbs
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String ycbs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.cjqk
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String cjqk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.shhj_cfpfss
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String shhjCfpfss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.shhj_rllx
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String shhjRllx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.shhj_ys
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String shhjYs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.shhj_cs
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String shhjCs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.shhj_qcl
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private String shhjQcl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.doctor_id
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private Integer doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.create_time
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.last_update_time
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.create_user_id
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.patient_id
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private Integer patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.del_flag
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private Boolean delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.has_cover
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private Byte hasCover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_basic_info.hospital_id
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    private Integer hospitalId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.id
     *
     * @return the value of phr_basic_info.id
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.id
     *
     * @param id the value for phr_basic_info.id
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.name
     *
     * @return the value of phr_basic_info.name
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.name
     *
     * @param name the value for phr_basic_info.name
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.user_no
     *
     * @return the value of phr_basic_info.user_no
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.user_no
     *
     * @param userNo the value for phr_basic_info.user_no
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.sex
     *
     * @return the value of phr_basic_info.sex
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.sex
     *
     * @param sex the value for phr_basic_info.sex
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.birthday
     *
     * @return the value of phr_basic_info.birthday
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.birthday
     *
     * @param birthday the value for phr_basic_info.birthday
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.id_card_no
     *
     * @return the value of phr_basic_info.id_card_no
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.id_card_no
     *
     * @param idCardNo the value for phr_basic_info.id_card_no
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.work_unit
     *
     * @return the value of phr_basic_info.work_unit
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getWorkUnit() {
        return workUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.work_unit
     *
     * @param workUnit the value for phr_basic_info.work_unit
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setWorkUnit(String workUnit) {
        this.workUnit = workUnit == null ? null : workUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.tel
     *
     * @return the value of phr_basic_info.tel
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.tel
     *
     * @param tel the value for phr_basic_info.tel
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.linkman
     *
     * @return the value of phr_basic_info.linkman
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.linkman
     *
     * @param linkman the value for phr_basic_info.linkman
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.linkman_tel
     *
     * @return the value of phr_basic_info.linkman_tel
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getLinkmanTel() {
        return linkmanTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.linkman_tel
     *
     * @param linkmanTel the value for phr_basic_info.linkman_tel
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setLinkmanTel(String linkmanTel) {
        this.linkmanTel = linkmanTel == null ? null : linkmanTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.resident_type
     *
     * @return the value of phr_basic_info.resident_type
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getResidentType() {
        return residentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.resident_type
     *
     * @param residentType the value for phr_basic_info.resident_type
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setResidentType(String residentType) {
        this.residentType = residentType == null ? null : residentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.nation
     *
     * @return the value of phr_basic_info.nation
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.nation
     *
     * @param nation the value for phr_basic_info.nation
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.nation_name
     *
     * @return the value of phr_basic_info.nation_name
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getNationName() {
        return nationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.nation_name
     *
     * @param nationName the value for phr_basic_info.nation_name
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setNationName(String nationName) {
        this.nationName = nationName == null ? null : nationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.blood_type
     *
     * @return the value of phr_basic_info.blood_type
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getBloodType() {
        return bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.blood_type
     *
     * @param bloodType the value for phr_basic_info.blood_type
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType == null ? null : bloodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.rh_type
     *
     * @return the value of phr_basic_info.rh_type
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getRhType() {
        return rhType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.rh_type
     *
     * @param rhType the value for phr_basic_info.rh_type
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setRhType(String rhType) {
        this.rhType = rhType == null ? null : rhType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.degree
     *
     * @return the value of phr_basic_info.degree
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.degree
     *
     * @param degree the value for phr_basic_info.degree
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.profession
     *
     * @return the value of phr_basic_info.profession
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.profession
     *
     * @param profession the value for phr_basic_info.profession
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.marital_status
     *
     * @return the value of phr_basic_info.marital_status
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.marital_status
     *
     * @param maritalStatus the value for phr_basic_info.marital_status
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus == null ? null : maritalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.pay_type
     *
     * @return the value of phr_basic_info.pay_type
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.pay_type
     *
     * @param payType the value for phr_basic_info.pay_type
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.pay_type_other
     *
     * @return the value of phr_basic_info.pay_type_other
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getPayTypeOther() {
        return payTypeOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.pay_type_other
     *
     * @param payTypeOther the value for phr_basic_info.pay_type_other
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setPayTypeOther(String payTypeOther) {
        this.payTypeOther = payTypeOther == null ? null : payTypeOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.ywgms
     *
     * @return the value of phr_basic_info.ywgms
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getYwgms() {
        return ywgms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.ywgms
     *
     * @param ywgms the value for phr_basic_info.ywgms
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setYwgms(String ywgms) {
        this.ywgms = ywgms == null ? null : ywgms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.ywgms_name
     *
     * @return the value of phr_basic_info.ywgms_name
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getYwgmsName() {
        return ywgmsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.ywgms_name
     *
     * @param ywgmsName the value for phr_basic_info.ywgms_name
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setYwgmsName(String ywgmsName) {
        this.ywgmsName = ywgmsName == null ? null : ywgmsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.bls
     *
     * @return the value of phr_basic_info.bls
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getBls() {
        return bls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.bls
     *
     * @param bls the value for phr_basic_info.bls
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setBls(String bls) {
        this.bls = bls == null ? null : bls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.jws_disease_des
     *
     * @return the value of phr_basic_info.jws_disease_des
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getJwsDiseaseDes() {
        return jwsDiseaseDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.jws_disease_des
     *
     * @param jwsDiseaseDes the value for phr_basic_info.jws_disease_des
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setJwsDiseaseDes(String jwsDiseaseDes) {
        this.jwsDiseaseDes = jwsDiseaseDes == null ? null : jwsDiseaseDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.jws_operation_des
     *
     * @return the value of phr_basic_info.jws_operation_des
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getJwsOperationDes() {
        return jwsOperationDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.jws_operation_des
     *
     * @param jwsOperationDes the value for phr_basic_info.jws_operation_des
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setJwsOperationDes(String jwsOperationDes) {
        this.jwsOperationDes = jwsOperationDes == null ? null : jwsOperationDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.jws_trauma_des
     *
     * @return the value of phr_basic_info.jws_trauma_des
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getJwsTraumaDes() {
        return jwsTraumaDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.jws_trauma_des
     *
     * @param jwsTraumaDes the value for phr_basic_info.jws_trauma_des
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setJwsTraumaDes(String jwsTraumaDes) {
        this.jwsTraumaDes = jwsTraumaDes == null ? null : jwsTraumaDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.jws_transfusion_des
     *
     * @return the value of phr_basic_info.jws_transfusion_des
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getJwsTransfusionDes() {
        return jwsTransfusionDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.jws_transfusion_des
     *
     * @param jwsTransfusionDes the value for phr_basic_info.jws_transfusion_des
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setJwsTransfusionDes(String jwsTransfusionDes) {
        this.jwsTransfusionDes = jwsTransfusionDes == null ? null : jwsTransfusionDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.jzs_fq
     *
     * @return the value of phr_basic_info.jzs_fq
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getJzsFq() {
        return jzsFq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.jzs_fq
     *
     * @param jzsFq the value for phr_basic_info.jzs_fq
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setJzsFq(String jzsFq) {
        this.jzsFq = jzsFq == null ? null : jzsFq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.jzs_mq
     *
     * @return the value of phr_basic_info.jzs_mq
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getJzsMq() {
        return jzsMq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.jzs_mq
     *
     * @param jzsMq the value for phr_basic_info.jzs_mq
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setJzsMq(String jzsMq) {
        this.jzsMq = jzsMq == null ? null : jzsMq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.jzs_xdjm
     *
     * @return the value of phr_basic_info.jzs_xdjm
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getJzsXdjm() {
        return jzsXdjm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.jzs_xdjm
     *
     * @param jzsXdjm the value for phr_basic_info.jzs_xdjm
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setJzsXdjm(String jzsXdjm) {
        this.jzsXdjm = jzsXdjm == null ? null : jzsXdjm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.jzs_zn
     *
     * @return the value of phr_basic_info.jzs_zn
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getJzsZn() {
        return jzsZn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.jzs_zn
     *
     * @param jzsZn the value for phr_basic_info.jzs_zn
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setJzsZn(String jzsZn) {
        this.jzsZn = jzsZn == null ? null : jzsZn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.ycbs
     *
     * @return the value of phr_basic_info.ycbs
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getYcbs() {
        return ycbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.ycbs
     *
     * @param ycbs the value for phr_basic_info.ycbs
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setYcbs(String ycbs) {
        this.ycbs = ycbs == null ? null : ycbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.cjqk
     *
     * @return the value of phr_basic_info.cjqk
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getCjqk() {
        return cjqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.cjqk
     *
     * @param cjqk the value for phr_basic_info.cjqk
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setCjqk(String cjqk) {
        this.cjqk = cjqk == null ? null : cjqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.shhj_cfpfss
     *
     * @return the value of phr_basic_info.shhj_cfpfss
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getShhjCfpfss() {
        return shhjCfpfss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.shhj_cfpfss
     *
     * @param shhjCfpfss the value for phr_basic_info.shhj_cfpfss
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setShhjCfpfss(String shhjCfpfss) {
        this.shhjCfpfss = shhjCfpfss == null ? null : shhjCfpfss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.shhj_rllx
     *
     * @return the value of phr_basic_info.shhj_rllx
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getShhjRllx() {
        return shhjRllx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.shhj_rllx
     *
     * @param shhjRllx the value for phr_basic_info.shhj_rllx
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setShhjRllx(String shhjRllx) {
        this.shhjRllx = shhjRllx == null ? null : shhjRllx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.shhj_ys
     *
     * @return the value of phr_basic_info.shhj_ys
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getShhjYs() {
        return shhjYs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.shhj_ys
     *
     * @param shhjYs the value for phr_basic_info.shhj_ys
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setShhjYs(String shhjYs) {
        this.shhjYs = shhjYs == null ? null : shhjYs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.shhj_cs
     *
     * @return the value of phr_basic_info.shhj_cs
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getShhjCs() {
        return shhjCs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.shhj_cs
     *
     * @param shhjCs the value for phr_basic_info.shhj_cs
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setShhjCs(String shhjCs) {
        this.shhjCs = shhjCs == null ? null : shhjCs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.shhj_qcl
     *
     * @return the value of phr_basic_info.shhj_qcl
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public String getShhjQcl() {
        return shhjQcl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.shhj_qcl
     *
     * @param shhjQcl the value for phr_basic_info.shhj_qcl
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setShhjQcl(String shhjQcl) {
        this.shhjQcl = shhjQcl == null ? null : shhjQcl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.doctor_id
     *
     * @return the value of phr_basic_info.doctor_id
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.doctor_id
     *
     * @param doctorId the value for phr_basic_info.doctor_id
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.create_time
     *
     * @return the value of phr_basic_info.create_time
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.create_time
     *
     * @param createTime the value for phr_basic_info.create_time
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.last_update_time
     *
     * @return the value of phr_basic_info.last_update_time
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.last_update_time
     *
     * @param lastUpdateTime the value for phr_basic_info.last_update_time
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.create_user_id
     *
     * @return the value of phr_basic_info.create_user_id
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.create_user_id
     *
     * @param createUserId the value for phr_basic_info.create_user_id
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.patient_id
     *
     * @return the value of phr_basic_info.patient_id
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.patient_id
     *
     * @param patientId the value for phr_basic_info.patient_id
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.del_flag
     *
     * @return the value of phr_basic_info.del_flag
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.del_flag
     *
     * @param delFlag the value for phr_basic_info.del_flag
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.has_cover
     *
     * @return the value of phr_basic_info.has_cover
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public Byte getHasCover() {
        return hasCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.has_cover
     *
     * @param hasCover the value for phr_basic_info.has_cover
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setHasCover(Byte hasCover) {
        this.hasCover = hasCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_basic_info.hospital_id
     *
     * @return the value of phr_basic_info.hospital_id
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_basic_info.hospital_id
     *
     * @param hospitalId the value for phr_basic_info.hospital_id
     *
     * @mbggenerated Mon Jun 12 21:00:54 CST 2017
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }
}