package com.lhfeiyu.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PhrCoverExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phr_cover
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phr_cover
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phr_cover
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phr_cover
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public PhrCoverExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phr_cover
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phr_cover
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phr_cover
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phr_cover
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phr_cover
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phr_cover
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phr_cover
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phr_cover
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phr_cover
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phr_cover
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table phr_cover
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andXzzIsNull() {
            addCriterion("xzz is null");
            return (Criteria) this;
        }

        public Criteria andXzzIsNotNull() {
            addCriterion("xzz is not null");
            return (Criteria) this;
        }

        public Criteria andXzzEqualTo(String value) {
            addCriterion("xzz =", value, "xzz");
            return (Criteria) this;
        }

        public Criteria andXzzNotEqualTo(String value) {
            addCriterion("xzz <>", value, "xzz");
            return (Criteria) this;
        }

        public Criteria andXzzGreaterThan(String value) {
            addCriterion("xzz >", value, "xzz");
            return (Criteria) this;
        }

        public Criteria andXzzGreaterThanOrEqualTo(String value) {
            addCriterion("xzz >=", value, "xzz");
            return (Criteria) this;
        }

        public Criteria andXzzLessThan(String value) {
            addCriterion("xzz <", value, "xzz");
            return (Criteria) this;
        }

        public Criteria andXzzLessThanOrEqualTo(String value) {
            addCriterion("xzz <=", value, "xzz");
            return (Criteria) this;
        }

        public Criteria andXzzLike(String value) {
            addCriterion("xzz like", value, "xzz");
            return (Criteria) this;
        }

        public Criteria andXzzNotLike(String value) {
            addCriterion("xzz not like", value, "xzz");
            return (Criteria) this;
        }

        public Criteria andXzzIn(List<String> values) {
            addCriterion("xzz in", values, "xzz");
            return (Criteria) this;
        }

        public Criteria andXzzNotIn(List<String> values) {
            addCriterion("xzz not in", values, "xzz");
            return (Criteria) this;
        }

        public Criteria andXzzBetween(String value1, String value2) {
            addCriterion("xzz between", value1, value2, "xzz");
            return (Criteria) this;
        }

        public Criteria andXzzNotBetween(String value1, String value2) {
            addCriterion("xzz not between", value1, value2, "xzz");
            return (Criteria) this;
        }

        public Criteria andHjdzIsNull() {
            addCriterion("hjdz is null");
            return (Criteria) this;
        }

        public Criteria andHjdzIsNotNull() {
            addCriterion("hjdz is not null");
            return (Criteria) this;
        }

        public Criteria andHjdzEqualTo(String value) {
            addCriterion("hjdz =", value, "hjdz");
            return (Criteria) this;
        }

        public Criteria andHjdzNotEqualTo(String value) {
            addCriterion("hjdz <>", value, "hjdz");
            return (Criteria) this;
        }

        public Criteria andHjdzGreaterThan(String value) {
            addCriterion("hjdz >", value, "hjdz");
            return (Criteria) this;
        }

        public Criteria andHjdzGreaterThanOrEqualTo(String value) {
            addCriterion("hjdz >=", value, "hjdz");
            return (Criteria) this;
        }

        public Criteria andHjdzLessThan(String value) {
            addCriterion("hjdz <", value, "hjdz");
            return (Criteria) this;
        }

        public Criteria andHjdzLessThanOrEqualTo(String value) {
            addCriterion("hjdz <=", value, "hjdz");
            return (Criteria) this;
        }

        public Criteria andHjdzLike(String value) {
            addCriterion("hjdz like", value, "hjdz");
            return (Criteria) this;
        }

        public Criteria andHjdzNotLike(String value) {
            addCriterion("hjdz not like", value, "hjdz");
            return (Criteria) this;
        }

        public Criteria andHjdzIn(List<String> values) {
            addCriterion("hjdz in", values, "hjdz");
            return (Criteria) this;
        }

        public Criteria andHjdzNotIn(List<String> values) {
            addCriterion("hjdz not in", values, "hjdz");
            return (Criteria) this;
        }

        public Criteria andHjdzBetween(String value1, String value2) {
            addCriterion("hjdz between", value1, value2, "hjdz");
            return (Criteria) this;
        }

        public Criteria andHjdzNotBetween(String value1, String value2) {
            addCriterion("hjdz not between", value1, value2, "hjdz");
            return (Criteria) this;
        }

        public Criteria andLxdhIsNull() {
            addCriterion("lxdh is null");
            return (Criteria) this;
        }

        public Criteria andLxdhIsNotNull() {
            addCriterion("lxdh is not null");
            return (Criteria) this;
        }

        public Criteria andLxdhEqualTo(String value) {
            addCriterion("lxdh =", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhNotEqualTo(String value) {
            addCriterion("lxdh <>", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhGreaterThan(String value) {
            addCriterion("lxdh >", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhGreaterThanOrEqualTo(String value) {
            addCriterion("lxdh >=", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhLessThan(String value) {
            addCriterion("lxdh <", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhLessThanOrEqualTo(String value) {
            addCriterion("lxdh <=", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhLike(String value) {
            addCriterion("lxdh like", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhNotLike(String value) {
            addCriterion("lxdh not like", value, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhIn(List<String> values) {
            addCriterion("lxdh in", values, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhNotIn(List<String> values) {
            addCriterion("lxdh not in", values, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhBetween(String value1, String value2) {
            addCriterion("lxdh between", value1, value2, "lxdh");
            return (Criteria) this;
        }

        public Criteria andLxdhNotBetween(String value1, String value2) {
            addCriterion("lxdh not between", value1, value2, "lxdh");
            return (Criteria) this;
        }

        public Criteria andXzmcIsNull() {
            addCriterion("xzmc is null");
            return (Criteria) this;
        }

        public Criteria andXzmcIsNotNull() {
            addCriterion("xzmc is not null");
            return (Criteria) this;
        }

        public Criteria andXzmcEqualTo(String value) {
            addCriterion("xzmc =", value, "xzmc");
            return (Criteria) this;
        }

        public Criteria andXzmcNotEqualTo(String value) {
            addCriterion("xzmc <>", value, "xzmc");
            return (Criteria) this;
        }

        public Criteria andXzmcGreaterThan(String value) {
            addCriterion("xzmc >", value, "xzmc");
            return (Criteria) this;
        }

        public Criteria andXzmcGreaterThanOrEqualTo(String value) {
            addCriterion("xzmc >=", value, "xzmc");
            return (Criteria) this;
        }

        public Criteria andXzmcLessThan(String value) {
            addCriterion("xzmc <", value, "xzmc");
            return (Criteria) this;
        }

        public Criteria andXzmcLessThanOrEqualTo(String value) {
            addCriterion("xzmc <=", value, "xzmc");
            return (Criteria) this;
        }

        public Criteria andXzmcLike(String value) {
            addCriterion("xzmc like", value, "xzmc");
            return (Criteria) this;
        }

        public Criteria andXzmcNotLike(String value) {
            addCriterion("xzmc not like", value, "xzmc");
            return (Criteria) this;
        }

        public Criteria andXzmcIn(List<String> values) {
            addCriterion("xzmc in", values, "xzmc");
            return (Criteria) this;
        }

        public Criteria andXzmcNotIn(List<String> values) {
            addCriterion("xzmc not in", values, "xzmc");
            return (Criteria) this;
        }

        public Criteria andXzmcBetween(String value1, String value2) {
            addCriterion("xzmc between", value1, value2, "xzmc");
            return (Criteria) this;
        }

        public Criteria andXzmcNotBetween(String value1, String value2) {
            addCriterion("xzmc not between", value1, value2, "xzmc");
            return (Criteria) this;
        }

        public Criteria andCwhmcIsNull() {
            addCriterion("cwhmc is null");
            return (Criteria) this;
        }

        public Criteria andCwhmcIsNotNull() {
            addCriterion("cwhmc is not null");
            return (Criteria) this;
        }

        public Criteria andCwhmcEqualTo(String value) {
            addCriterion("cwhmc =", value, "cwhmc");
            return (Criteria) this;
        }

        public Criteria andCwhmcNotEqualTo(String value) {
            addCriterion("cwhmc <>", value, "cwhmc");
            return (Criteria) this;
        }

        public Criteria andCwhmcGreaterThan(String value) {
            addCriterion("cwhmc >", value, "cwhmc");
            return (Criteria) this;
        }

        public Criteria andCwhmcGreaterThanOrEqualTo(String value) {
            addCriterion("cwhmc >=", value, "cwhmc");
            return (Criteria) this;
        }

        public Criteria andCwhmcLessThan(String value) {
            addCriterion("cwhmc <", value, "cwhmc");
            return (Criteria) this;
        }

        public Criteria andCwhmcLessThanOrEqualTo(String value) {
            addCriterion("cwhmc <=", value, "cwhmc");
            return (Criteria) this;
        }

        public Criteria andCwhmcLike(String value) {
            addCriterion("cwhmc like", value, "cwhmc");
            return (Criteria) this;
        }

        public Criteria andCwhmcNotLike(String value) {
            addCriterion("cwhmc not like", value, "cwhmc");
            return (Criteria) this;
        }

        public Criteria andCwhmcIn(List<String> values) {
            addCriterion("cwhmc in", values, "cwhmc");
            return (Criteria) this;
        }

        public Criteria andCwhmcNotIn(List<String> values) {
            addCriterion("cwhmc not in", values, "cwhmc");
            return (Criteria) this;
        }

        public Criteria andCwhmcBetween(String value1, String value2) {
            addCriterion("cwhmc between", value1, value2, "cwhmc");
            return (Criteria) this;
        }

        public Criteria andCwhmcNotBetween(String value1, String value2) {
            addCriterion("cwhmc not between", value1, value2, "cwhmc");
            return (Criteria) this;
        }

        public Criteria andJddwIsNull() {
            addCriterion("jddw is null");
            return (Criteria) this;
        }

        public Criteria andJddwIsNotNull() {
            addCriterion("jddw is not null");
            return (Criteria) this;
        }

        public Criteria andJddwEqualTo(String value) {
            addCriterion("jddw =", value, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwNotEqualTo(String value) {
            addCriterion("jddw <>", value, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwGreaterThan(String value) {
            addCriterion("jddw >", value, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwGreaterThanOrEqualTo(String value) {
            addCriterion("jddw >=", value, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwLessThan(String value) {
            addCriterion("jddw <", value, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwLessThanOrEqualTo(String value) {
            addCriterion("jddw <=", value, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwLike(String value) {
            addCriterion("jddw like", value, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwNotLike(String value) {
            addCriterion("jddw not like", value, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwIn(List<String> values) {
            addCriterion("jddw in", values, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwNotIn(List<String> values) {
            addCriterion("jddw not in", values, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwBetween(String value1, String value2) {
            addCriterion("jddw between", value1, value2, "jddw");
            return (Criteria) this;
        }

        public Criteria andJddwNotBetween(String value1, String value2) {
            addCriterion("jddw not between", value1, value2, "jddw");
            return (Criteria) this;
        }

        public Criteria andJdrIsNull() {
            addCriterion("jdr is null");
            return (Criteria) this;
        }

        public Criteria andJdrIsNotNull() {
            addCriterion("jdr is not null");
            return (Criteria) this;
        }

        public Criteria andJdrEqualTo(String value) {
            addCriterion("jdr =", value, "jdr");
            return (Criteria) this;
        }

        public Criteria andJdrNotEqualTo(String value) {
            addCriterion("jdr <>", value, "jdr");
            return (Criteria) this;
        }

        public Criteria andJdrGreaterThan(String value) {
            addCriterion("jdr >", value, "jdr");
            return (Criteria) this;
        }

        public Criteria andJdrGreaterThanOrEqualTo(String value) {
            addCriterion("jdr >=", value, "jdr");
            return (Criteria) this;
        }

        public Criteria andJdrLessThan(String value) {
            addCriterion("jdr <", value, "jdr");
            return (Criteria) this;
        }

        public Criteria andJdrLessThanOrEqualTo(String value) {
            addCriterion("jdr <=", value, "jdr");
            return (Criteria) this;
        }

        public Criteria andJdrLike(String value) {
            addCriterion("jdr like", value, "jdr");
            return (Criteria) this;
        }

        public Criteria andJdrNotLike(String value) {
            addCriterion("jdr not like", value, "jdr");
            return (Criteria) this;
        }

        public Criteria andJdrIn(List<String> values) {
            addCriterion("jdr in", values, "jdr");
            return (Criteria) this;
        }

        public Criteria andJdrNotIn(List<String> values) {
            addCriterion("jdr not in", values, "jdr");
            return (Criteria) this;
        }

        public Criteria andJdrBetween(String value1, String value2) {
            addCriterion("jdr between", value1, value2, "jdr");
            return (Criteria) this;
        }

        public Criteria andJdrNotBetween(String value1, String value2) {
            addCriterion("jdr not between", value1, value2, "jdr");
            return (Criteria) this;
        }

        public Criteria andZrysIsNull() {
            addCriterion("zrys is null");
            return (Criteria) this;
        }

        public Criteria andZrysIsNotNull() {
            addCriterion("zrys is not null");
            return (Criteria) this;
        }

        public Criteria andZrysEqualTo(String value) {
            addCriterion("zrys =", value, "zrys");
            return (Criteria) this;
        }

        public Criteria andZrysNotEqualTo(String value) {
            addCriterion("zrys <>", value, "zrys");
            return (Criteria) this;
        }

        public Criteria andZrysGreaterThan(String value) {
            addCriterion("zrys >", value, "zrys");
            return (Criteria) this;
        }

        public Criteria andZrysGreaterThanOrEqualTo(String value) {
            addCriterion("zrys >=", value, "zrys");
            return (Criteria) this;
        }

        public Criteria andZrysLessThan(String value) {
            addCriterion("zrys <", value, "zrys");
            return (Criteria) this;
        }

        public Criteria andZrysLessThanOrEqualTo(String value) {
            addCriterion("zrys <=", value, "zrys");
            return (Criteria) this;
        }

        public Criteria andZrysLike(String value) {
            addCriterion("zrys like", value, "zrys");
            return (Criteria) this;
        }

        public Criteria andZrysNotLike(String value) {
            addCriterion("zrys not like", value, "zrys");
            return (Criteria) this;
        }

        public Criteria andZrysIn(List<String> values) {
            addCriterion("zrys in", values, "zrys");
            return (Criteria) this;
        }

        public Criteria andZrysNotIn(List<String> values) {
            addCriterion("zrys not in", values, "zrys");
            return (Criteria) this;
        }

        public Criteria andZrysBetween(String value1, String value2) {
            addCriterion("zrys between", value1, value2, "zrys");
            return (Criteria) this;
        }

        public Criteria andZrysNotBetween(String value1, String value2) {
            addCriterion("zrys not between", value1, value2, "zrys");
            return (Criteria) this;
        }

        public Criteria andJdrqIsNull() {
            addCriterion("jdrq is null");
            return (Criteria) this;
        }

        public Criteria andJdrqIsNotNull() {
            addCriterion("jdrq is not null");
            return (Criteria) this;
        }

        public Criteria andJdrqEqualTo(Date value) {
            addCriterionForJDBCDate("jdrq =", value, "jdrq");
            return (Criteria) this;
        }

        public Criteria andJdrqNotEqualTo(Date value) {
            addCriterionForJDBCDate("jdrq <>", value, "jdrq");
            return (Criteria) this;
        }

        public Criteria andJdrqGreaterThan(Date value) {
            addCriterionForJDBCDate("jdrq >", value, "jdrq");
            return (Criteria) this;
        }

        public Criteria andJdrqGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("jdrq >=", value, "jdrq");
            return (Criteria) this;
        }

        public Criteria andJdrqLessThan(Date value) {
            addCriterionForJDBCDate("jdrq <", value, "jdrq");
            return (Criteria) this;
        }

        public Criteria andJdrqLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("jdrq <=", value, "jdrq");
            return (Criteria) this;
        }

        public Criteria andJdrqIn(List<Date> values) {
            addCriterionForJDBCDate("jdrq in", values, "jdrq");
            return (Criteria) this;
        }

        public Criteria andJdrqNotIn(List<Date> values) {
            addCriterionForJDBCDate("jdrq not in", values, "jdrq");
            return (Criteria) this;
        }

        public Criteria andJdrqBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("jdrq between", value1, value2, "jdrq");
            return (Criteria) this;
        }

        public Criteria andJdrqNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("jdrq not between", value1, value2, "jdrq");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIsNull() {
            addCriterion("doctor_id is null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIsNotNull() {
            addCriterion("doctor_id is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdEqualTo(Integer value) {
            addCriterion("doctor_id =", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotEqualTo(Integer value) {
            addCriterion("doctor_id <>", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThan(Integer value) {
            addCriterion("doctor_id >", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("doctor_id >=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThan(Integer value) {
            addCriterion("doctor_id <", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThanOrEqualTo(Integer value) {
            addCriterion("doctor_id <=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIn(List<Integer> values) {
            addCriterion("doctor_id in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotIn(List<Integer> values) {
            addCriterion("doctor_id not in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdBetween(Integer value1, Integer value2) {
            addCriterion("doctor_id between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("doctor_id not between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Integer value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Integer value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Integer value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Integer value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Integer> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Integer> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNull() {
            addCriterion("patient_id is null");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNotNull() {
            addCriterion("patient_id is not null");
            return (Criteria) this;
        }

        public Criteria andPatientIdEqualTo(Integer value) {
            addCriterion("patient_id =", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotEqualTo(Integer value) {
            addCriterion("patient_id <>", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThan(Integer value) {
            addCriterion("patient_id >", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("patient_id >=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThan(Integer value) {
            addCriterion("patient_id <", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThanOrEqualTo(Integer value) {
            addCriterion("patient_id <=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIn(List<Integer> values) {
            addCriterion("patient_id in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotIn(List<Integer> values) {
            addCriterion("patient_id not in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdBetween(Integer value1, Integer value2) {
            addCriterion("patient_id between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotBetween(Integer value1, Integer value2) {
            addCriterion("patient_id not between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdIsNull() {
            addCriterion("hospital_id is null");
            return (Criteria) this;
        }

        public Criteria andHospitalIdIsNotNull() {
            addCriterion("hospital_id is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalIdEqualTo(Integer value) {
            addCriterion("hospital_id =", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotEqualTo(Integer value) {
            addCriterion("hospital_id <>", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdGreaterThan(Integer value) {
            addCriterion("hospital_id >", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("hospital_id >=", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdLessThan(Integer value) {
            addCriterion("hospital_id <", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdLessThanOrEqualTo(Integer value) {
            addCriterion("hospital_id <=", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdIn(List<Integer> values) {
            addCriterion("hospital_id in", values, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotIn(List<Integer> values) {
            addCriterion("hospital_id not in", values, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdBetween(Integer value1, Integer value2) {
            addCriterion("hospital_id between", value1, value2, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotBetween(Integer value1, Integer value2) {
            addCriterion("hospital_id not between", value1, value2, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andBasicInfoIdIsNull() {
            addCriterion("basic_info_id is null");
            return (Criteria) this;
        }

        public Criteria andBasicInfoIdIsNotNull() {
            addCriterion("basic_info_id is not null");
            return (Criteria) this;
        }

        public Criteria andBasicInfoIdEqualTo(Integer value) {
            addCriterion("basic_info_id =", value, "basicInfoId");
            return (Criteria) this;
        }

        public Criteria andBasicInfoIdNotEqualTo(Integer value) {
            addCriterion("basic_info_id <>", value, "basicInfoId");
            return (Criteria) this;
        }

        public Criteria andBasicInfoIdGreaterThan(Integer value) {
            addCriterion("basic_info_id >", value, "basicInfoId");
            return (Criteria) this;
        }

        public Criteria andBasicInfoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("basic_info_id >=", value, "basicInfoId");
            return (Criteria) this;
        }

        public Criteria andBasicInfoIdLessThan(Integer value) {
            addCriterion("basic_info_id <", value, "basicInfoId");
            return (Criteria) this;
        }

        public Criteria andBasicInfoIdLessThanOrEqualTo(Integer value) {
            addCriterion("basic_info_id <=", value, "basicInfoId");
            return (Criteria) this;
        }

        public Criteria andBasicInfoIdIn(List<Integer> values) {
            addCriterion("basic_info_id in", values, "basicInfoId");
            return (Criteria) this;
        }

        public Criteria andBasicInfoIdNotIn(List<Integer> values) {
            addCriterion("basic_info_id not in", values, "basicInfoId");
            return (Criteria) this;
        }

        public Criteria andBasicInfoIdBetween(Integer value1, Integer value2) {
            addCriterion("basic_info_id between", value1, value2, "basicInfoId");
            return (Criteria) this;
        }

        public Criteria andBasicInfoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("basic_info_id not between", value1, value2, "basicInfoId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table phr_cover
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 08 01:02:23 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table phr_cover
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}