package com.lhfeiyu.po;

import java.util.Date;

public class PhrCover {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_cover.id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_cover.name
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_cover.xzz
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    private String xzz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_cover.hjdz
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    private String hjdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_cover.lxdh
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    private String lxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_cover.xzmc
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    private String xzmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_cover.cwhmc
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    private String cwhmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_cover.jddw
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    private String jddw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_cover.jdr
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    private String jdr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_cover.zrys
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    private String zrys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_cover.jdrq
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    private Date jdrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_cover.doctor_id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    private Integer doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_cover.create_user_id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_cover.create_time
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_cover.patient_id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    private Integer patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_cover.hospital_id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    private Integer hospitalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_cover.basic_info_id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    private Integer basicInfoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_cover.id
     *
     * @return the value of phr_cover.id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_cover.id
     *
     * @param id the value for phr_cover.id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_cover.name
     *
     * @return the value of phr_cover.name
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_cover.name
     *
     * @param name the value for phr_cover.name
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_cover.xzz
     *
     * @return the value of phr_cover.xzz
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public String getXzz() {
        return xzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_cover.xzz
     *
     * @param xzz the value for phr_cover.xzz
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setXzz(String xzz) {
        this.xzz = xzz == null ? null : xzz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_cover.hjdz
     *
     * @return the value of phr_cover.hjdz
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public String getHjdz() {
        return hjdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_cover.hjdz
     *
     * @param hjdz the value for phr_cover.hjdz
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setHjdz(String hjdz) {
        this.hjdz = hjdz == null ? null : hjdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_cover.lxdh
     *
     * @return the value of phr_cover.lxdh
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_cover.lxdh
     *
     * @param lxdh the value for phr_cover.lxdh
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_cover.xzmc
     *
     * @return the value of phr_cover.xzmc
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public String getXzmc() {
        return xzmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_cover.xzmc
     *
     * @param xzmc the value for phr_cover.xzmc
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setXzmc(String xzmc) {
        this.xzmc = xzmc == null ? null : xzmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_cover.cwhmc
     *
     * @return the value of phr_cover.cwhmc
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public String getCwhmc() {
        return cwhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_cover.cwhmc
     *
     * @param cwhmc the value for phr_cover.cwhmc
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setCwhmc(String cwhmc) {
        this.cwhmc = cwhmc == null ? null : cwhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_cover.jddw
     *
     * @return the value of phr_cover.jddw
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public String getJddw() {
        return jddw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_cover.jddw
     *
     * @param jddw the value for phr_cover.jddw
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setJddw(String jddw) {
        this.jddw = jddw == null ? null : jddw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_cover.jdr
     *
     * @return the value of phr_cover.jdr
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public String getJdr() {
        return jdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_cover.jdr
     *
     * @param jdr the value for phr_cover.jdr
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setJdr(String jdr) {
        this.jdr = jdr == null ? null : jdr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_cover.zrys
     *
     * @return the value of phr_cover.zrys
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public String getZrys() {
        return zrys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_cover.zrys
     *
     * @param zrys the value for phr_cover.zrys
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setZrys(String zrys) {
        this.zrys = zrys == null ? null : zrys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_cover.jdrq
     *
     * @return the value of phr_cover.jdrq
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public Date getJdrq() {
        return jdrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_cover.jdrq
     *
     * @param jdrq the value for phr_cover.jdrq
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setJdrq(Date jdrq) {
        this.jdrq = jdrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_cover.doctor_id
     *
     * @return the value of phr_cover.doctor_id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_cover.doctor_id
     *
     * @param doctorId the value for phr_cover.doctor_id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_cover.create_user_id
     *
     * @return the value of phr_cover.create_user_id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_cover.create_user_id
     *
     * @param createUserId the value for phr_cover.create_user_id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_cover.create_time
     *
     * @return the value of phr_cover.create_time
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_cover.create_time
     *
     * @param createTime the value for phr_cover.create_time
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_cover.patient_id
     *
     * @return the value of phr_cover.patient_id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_cover.patient_id
     *
     * @param patientId the value for phr_cover.patient_id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_cover.hospital_id
     *
     * @return the value of phr_cover.hospital_id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_cover.hospital_id
     *
     * @param hospitalId the value for phr_cover.hospital_id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_cover.basic_info_id
     *
     * @return the value of phr_cover.basic_info_id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public Integer getBasicInfoId() {
        return basicInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_cover.basic_info_id
     *
     * @param basicInfoId the value for phr_cover.basic_info_id
     *
     * @mbggenerated Thu Jun 08 01:02:23 CST 2017
     */
    public void setBasicInfoId(Integer basicInfoId) {
        this.basicInfoId = basicInfoId;
    }
}