package com.lhfeiyu.po;

public class PhrArchiveNumber {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_archive_number.id
     *
     * @mbggenerated Wed Jun 28 20:24:18 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_archive_number.hospital_id
     *
     * @mbggenerated Wed Jun 28 20:24:18 CST 2017
     */
    private Integer hospitalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_archive_number.start_value
     *
     * @mbggenerated Wed Jun 28 20:24:18 CST 2017
     */
    private Integer startValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phr_archive_number.next_value
     *
     * @mbggenerated Wed Jun 28 20:24:18 CST 2017
     */
    private Integer nextValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_archive_number.id
     *
     * @return the value of phr_archive_number.id
     *
     * @mbggenerated Wed Jun 28 20:24:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_archive_number.id
     *
     * @param id the value for phr_archive_number.id
     *
     * @mbggenerated Wed Jun 28 20:24:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_archive_number.hospital_id
     *
     * @return the value of phr_archive_number.hospital_id
     *
     * @mbggenerated Wed Jun 28 20:24:18 CST 2017
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_archive_number.hospital_id
     *
     * @param hospitalId the value for phr_archive_number.hospital_id
     *
     * @mbggenerated Wed Jun 28 20:24:18 CST 2017
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_archive_number.start_value
     *
     * @return the value of phr_archive_number.start_value
     *
     * @mbggenerated Wed Jun 28 20:24:18 CST 2017
     */
    public Integer getStartValue() {
        return startValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_archive_number.start_value
     *
     * @param startValue the value for phr_archive_number.start_value
     *
     * @mbggenerated Wed Jun 28 20:24:18 CST 2017
     */
    public void setStartValue(Integer startValue) {
        this.startValue = startValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phr_archive_number.next_value
     *
     * @return the value of phr_archive_number.next_value
     *
     * @mbggenerated Wed Jun 28 20:24:18 CST 2017
     */
    public Integer getNextValue() {
        return nextValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phr_archive_number.next_value
     *
     * @param nextValue the value for phr_archive_number.next_value
     *
     * @mbggenerated Wed Jun 28 20:24:18 CST 2017
     */
    public void setNextValue(Integer nextValue) {
        this.nextValue = nextValue;
    }
}